name: Full-Stack Docker Build and Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Aikido Security Scan
        uses: AikidoSec/github-actions-workflow@v1.0.13
        with:
          secret-key: ${{ secrets.AIKIDO_API_KEY }}
          fail-on-dependency-scan: true
          fail-on-sast-scan: true
          minimum-severity: 'HIGH'

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211395678018:role/GitHubAction-ECR-Role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker-compose build backend
          docker tag backend:latest $ECR_REGISTRY/fullstack-backend:latest
          docker push $ECR_REGISTRY/fullstack-backend:latest

      - name: Build and Push Frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker-compose build frontend
          docker tag frontend:latest $ECR_REGISTRY/fullstack-frontend:latest
          docker push $ECR_REGISTRY/fullstack-frontend:latest
